#!/bin/sh

if [ "x${COVERITY_SCAN_PROJECT_NAME}" != "x" ] ; then exit 0; fi

cd $TRAVIS_BUILD_DIR/build
cmake -DOSX_PACKAGE=ON ..
make
ls
PKG=$(ls | grep -e "pkg$")

# https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/security.1.html
# https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/productsign.1.html
KEYCHAIN=build.keychain
security -v create-keychain -p temp_password ${KEYCHAIN}
security -v default-keychain -s ${KEYCHAIN}
security -v unlock-keychain -p temp_password ${KEYCHAIN}
security -v import /tmp/certificate.p12 -k ${KEYCHAIN} -P '' -T /usr/bin/productsign
security find-identity -v ${KEYCHAIN}
security find-identity -p codesigning -v ${KEYCHAIN}

productsign --keychain $KEYCHAIN --sign 65C15CDF09900263582867E9EAC9C8E9DDC080C6 ${PKG} ${PKG}_signed
rm ${PKG}
mv ${PKG}_signed ${PKG}

cd $TRAVIS_BUILD_DIR/build_tar
cmake -DOSX_PACKAGE=OFF -DENABLE_PACKAGING=ON ..
make && make package
ls
