#!/bin/sh

if [ "x${COVERITY_SCAN_PROJECT_NAME}" != "x" ] ; then exit 0; fi

cd $TRAVIS_BUILD_DIR/build
cmake -DOSX_PACKAGE=ON ..
make
ls
PKG=$(ls | grep -e "pkg$")

# https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/security.1.html
# https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/productsign.1.html
KEYCHAIN=build.keychain
security -v create-keychain -p temp_password ${KEYCHAIN}
security -v default-keychain -s ${KEYCHAIN}
security -v unlock-keychain -p temp_password ${KEYCHAIN}
ecurity find-identity -v ${KEYCHAIN}
security -v import /tmp/certificate.p12 -k ${KEYCHAIN} -P '' -T /usr/bin/productsign
productsign --keychain $KEYCHAIN --sign $PKG $PKG_signed
rm ${PKG}
mv ${PKG}_signed ${PKG}
rm ${KEYCHAIN}

cd $TRAVIS_BUILD_DIR/build_tar
cmake -DOSX_PACKAGE=OFF -DENABLE_PACKAGING=ON ..
make && make package
ls
